// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import mockSupabase from '../../utils/mockSupabase';

// Configuración para DEMO
const supabaseUrl = 'https://example.supabase.co';
const supabaseAnonKey = 'demo-key';

// En modo demo, usar mock
const supabase = import.meta.env.DEMO ? mockSupabase : createClient(supabaseUrl, supabaseAnonKey);

export default supabase;